#https://docs.github.com/en/actions/tutorials/build-and-test-code/go
name: Go Tests
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: [grlimit, zlog, backoff]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
          cache-dependency-path: |
            **/go.sum
      - name: Run tests
        working-directory: ${{ matrix.pkg }}
        run: go test -v -race -cover ./...
